# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_find3408(self):
    self.driver.get("https://www.centennialcollege.ca/")
    self.driver.set_window_size(1872, 1055)
    self.driver.find_element(By.ID, "searchTextBox").click()
    self.driver.find_element(By.ID, "searchTextBox").send_keys("3408")
    self.driver.find_element(By.ID, "searchTextBox").send_keys(Keys.ENTER)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Software Engineering Technician - Centennial College")))
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "Software Engineering Technician - Centennial College").click()
    self.vars["win2502"] = self.wait_for_window(2000)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//span[contains(text(), \'3408\')]")))
    assert self.driver.find_element(By.XPATH, "//span[contains(text(), \'3408\')]").text == "3408"
  
  def test_find3409(self):
    self.driver.get("https://www.centennialcollege.ca/")
    self.driver.set_window_size(1872, 1055)
    self.driver.find_element(By.ID, "searchTextBox").click()
    self.driver.find_element(By.ID, "searchTextBox").send_keys("3409")
    self.driver.find_element(By.ID, "searchTextBox").send_keys(Keys.ENTER)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Software Engineering Technology (Optional ... - Centennial College")))
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "Software Engineering Technology (Optional ... - Centennial College").click()
    self.vars["win2502"] = self.wait_for_window(2000)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//span[contains(text(), \'3409\')]")))
    assert self.driver.find_element(By.XPATH, "//span[contains(text(), \'3409\')]").text == "3409"
  
