CREATE TABLE product
(
    product_id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sku             VARCHAR(255),
    name            VARCHAR(255),
    description     VARCHAR(255),
    brand           VARCHAR(255),
    refill_quantity INTEGER,
    CONSTRAINT pk_product PRIMARY KEY (product_id)
);

ALTER TABLE product
    ADD CONSTRAINT uc_product_sku UNIQUE (sku);