CREATE TABLE "user"
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(255),
    password  VARCHAR(255),
    name      VARCHAR(255),
    email     VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);